languageCode = "en-us"
baseURL = "https://techpals-eu.github.io/website/"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/techpals.png"
    mobile_height = "100px"
    desktop = "images/logo/techpals.png"
    desktop_height = "150px"
    alt = "TechPals consultancy agency"

  [params.seo]
    meta_twitter_site = "@techpals"
    meta_twitter_creator = "@techpals"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Techpals'

[menu]
  # Main Menu
  [[menu.main]]
    name = "What We Do"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Who We Are"
      url = "/team/"
      weight = 2

  [[menu.main]]
      name = "Careers"
      url = "/careers/"
      weight = 3

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 4

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
      name = "Jobs"
      url = "/jobs/"
      weight = 2

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 3
